// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkxxohoykyyvmjzddtxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreHhvaG95a3l5dm1qemRkdHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDU3NTEsImV4cCI6MjA2MDg4MTc1MX0.Lza4YIDV_D--6l2Uv2ykX0s1EHqOA9T0bPwNsDHhmb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);